//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dive()
        {
            this.Scores = new HashSet<Score>();
        }
    
        public int DiveID { get; set; }
        public string Diver { get; set; }
        public int Competition { get; set; }
        public Nullable<int> DifficultyScore { get; set; }
        [Display(Name = "Dive group")]
        public int DiveCode1 { get; set; }
        [Display(Name = "Second digit")]
        public int DiveCode2 { get; set; }
        [Display(Name = "Number of half somersaults")]
        public int DiveCode3 { get; set; }
        [Display(Name = "Number of half twists")]
        public Nullable<int> DiveCode4 { get; set; }
        [Display(Name = "Body position")]
        public int DiveChar5 { get; set; }
        public int PlatformsHeight { get; set; }
    
        public virtual Competition Competition1 { get; set; }
        public virtual Competition Competition2 { get; set; }
        public virtual Competition Competition3 { get; set; }
        public virtual DiveChar5 DiveChar51 { get; set; }
        public virtual DiveChar5 DiveChar52 { get; set; }
        public virtual DiveChar5 DiveChar53 { get; set; }
        public virtual DiveCode1 DiveCode11 { get; set; }
        public virtual DiveCode1 DiveCode12 { get; set; }
        public virtual DiveCode1 DiveCode13 { get; set; }
        public virtual DiveCode2 DiveCode21 { get; set; }
        public virtual DiveCode2 DiveCode22 { get; set; }
        public virtual DiveCode2 DiveCode23 { get; set; }
        public virtual PlatformsHeight PlatformsHeight1 { get; set; }
        public virtual PlatformsHeight PlatformsHeight2 { get; set; }
        public virtual PlatformsHeight PlatformsHeight3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
        public object User { get; internal set; }
    }
}
