//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckDetail
    {
        public int TruckID { get; set; }
        public string TruckDescription { get; set; }
        public Nullable<int> TruckBrandID { get; set; }
        public string TruckColor { get; set; }
    
        public virtual TruckRefBrands TruckRefBrands { get; set; }
    }
}
